trigger:
  branches:
    include:
      - main

pool: 'Test agent'

variables:
  AZURE_WEBAPP_NAME: 'web-inmeta-learn'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - checkout: self

          - task: UseNode@1
            inputs:
              version: '20.x'
              checkLatest: true

          - script: |
              npm set cache .npm
              npm ci
              npm run build
            displayName: 'npm install and build'

          - script: |
              cp -R ./public ./.next/standalone/public
              cp -R ./.next/static ./.next/standalone/.next/static
            displayName: 'Copy static files'

          - task: PublishPipelineArtifact@1
            inputs:
              artifactName: 'app'
              targetPath: '.next/standalone'
            displayName: 'Upload artifact for deployment'

  - stage: Deploy
    dependsOn: Build
    jobs:
      - deployment: Deploy
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  inputs:
                    artifactName: 'app'
                    targetPath: '$(Pipeline.Workspace)'
                  displayName: 'Download artifact from build job'

                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: 'test-service-connection' # This should be your Azure service connection
                    appName: '$(AZURE_WEBAPP_NAME)'
                    appType: webApp
                    package: '$(Pipeline.Workspace)/app'
